Check the existence of PKGBUILD-TMP in the current folder

diff --git a/minos b/minos
--- a/minos
+++ b/minos
@@ -147,6 +147,12 @@ function help(){
 }
 
 
+
+if [ ! -f PKGBUILD-TMP ]; then
+    echo "Error there is no PKGBUILD-TMP in the current folder."
+    exit 1
+fi
+
 if [ "$1" == "--help" ] || [ "$1" == "-h" ];
 then
     help
